<div class="header">
       <div class="header-left">
        <i id="menu" class="fa-solid fa-bars"></i>
         <img src="https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/aaa79357-9476-4c1d-b9a8-6e881f2449d3/ddcs83v-0aa3d0b3-75d1-427d-8441-11156de89830.png/v1/fill/w_800,h_310,strp/the_boys_logo_png_by_buffy2ville_ddcs83v-fullview.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9MzEwIiwicGF0aCI6IlwvZlwvYWFhNzkzNTctOTQ3Ni00YzFkLWI5YTgtNmU4ODFmMjQ0OWQzXC9kZGNzODN2LTBhYTNkMGIzLTc1ZDEtNDI3ZC04NDQxLTExMTU2ZGU4OTgzMC5wbmciLCJ3aWR0aCI6Ijw9ODAwIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmltYWdlLm9wZXJhdGlvbnMiXX0.s-4HscwxDVvQee8R6-MH3dHJjhRkAZObBDf2xY8LZDI" alt="">
       </div>

       <div class="header-search">
           <form action="" method="get">
            <input type="text" name="">
            <button><i class="fa-solid fa-magnifying-glass"></i></button>
           </form>
       </div>

       <div class="header_icons">
       <i class="fa-solid fa-magnifying-glass display-this"></i>
       <i class="fa-solid fa-video"></i>
       <i class="fa-solid fa-circle-user"></i>
       <a href="#"><img src="https://i.pinimg.com/originals/cc/ef/1f/ccef1f065d2b429cc7fdbf183506c155.jpg" alt="Avatar Logo" style="width:40px;" class="rounded-pill"></a>
       </div>
  </div>