<div class="sidebar">
    <div class="sidebar-categories">
        <div class="sidebar-category">
           <i class="fa-solid fa-house"></i>
           <span>Home</span>
        </div>

        <div class="sidebar-category">
          <i class="fa-solid fa-fire-flame-curved"></i>
           <span>Mais curtidos</span>
        </div>

        <div class="sidebar-category">
           <i class="fa-solid fa-house"></i>
           <span>Home</span>
        </div>
    </div>
    <hr/>

    <div class="sidebar-categories">
        <div class="sidebar-category">
           <i class="fa-solid fa-house"></i>
           <span>Home</span>
        </div>

        <div class="sidebar-category">
          <i class="fa-solid fa-fire-flame-curved"></i>
           <span>Mais curtidos</span>
        </div>

        <div class="sidebar-category">
           <i class="fa-solid fa-house"></i>
           <span>Home</span>
        </div>
    </div>
    <hr/>
  </div>