<div class="videos">
    <h1>Pense em algo legal</h1>
    <div class="videos-container">
      <!--Inicio single video-->
      <div class="video">
        <div class="thumbnail">
          <img src="https://legendary-digital-network-assets.s3.amazonaws.com/wp-content/uploads/2022/06/10093529/Homelander-Taco-Bowl-The-Boys.jpg" alt="">
        </div>
        <div class="video-details">
          <div class="author">
            <img src="https://64.media.tumblr.com/fe1749dbc7695c88a4700faf8c2e004a/a267b157ec23e4a7-6b/s500x750/8b97317d8f8e0efecb2b1f0b817ad04ad75d61d5.png" alt="">
          </div>
          <div class="title">
            <h3>Homelander</h3>
            <a href="#">Link</a>
            <span>Post</span>
          </div>
        </div>
      </div>
      <!--Fim single video-->

       <!--Inicio single video-->
       <div class="video">
        <div class="thumbnail">
          <img src="https://legendary-digital-network-assets.s3.amazonaws.com/wp-content/uploads/2022/06/10093529/Homelander-Taco-Bowl-The-Boys.jpg" alt="">
        </div>
        <div class="video-details">
          <div class="author">
            <img src="https://64.media.tumblr.com/fe1749dbc7695c88a4700faf8c2e004a/a267b157ec23e4a7-6b/s500x750/8b97317d8f8e0efecb2b1f0b817ad04ad75d61d5.png" alt="">
          </div>
          <div class="title">
            <h3>Homelander</h3>
            <a href="#">Link</a>
            <span>Post</span>
          </div>
        </div>
      </div>
      <!--Fim single video-->

       <!--Inicio single video-->
       <div class="video">
        <div class="thumbnail">
          <img src="https://legendary-digital-network-assets.s3.amazonaws.com/wp-content/uploads/2022/06/10093529/Homelander-Taco-Bowl-The-Boys.jpg" alt="">
        </div>
        <div class="video-details">
          <div class="author">
            <img src="https://64.media.tumblr.com/fe1749dbc7695c88a4700faf8c2e004a/a267b157ec23e4a7-6b/s500x750/8b97317d8f8e0efecb2b1f0b817ad04ad75d61d5.png" alt="">
          </div>
          <div class="title">
            <h3>Homelander</h3>
            <a href="#">Link</a>
            <span>Post</span>
          </div>
        </div>
      </div>
      <!--Fim single video-->

       <!--Inicio single video-->
       <div class="video">
        <div class="thumbnail">
          <img src="https://legendary-digital-network-assets.s3.amazonaws.com/wp-content/uploads/2022/06/10093529/Homelander-Taco-Bowl-The-Boys.jpg" alt="">
        </div>
        <div class="video-details">
          <div class="author">
            <img src="https://64.media.tumblr.com/fe1749dbc7695c88a4700faf8c2e004a/a267b157ec23e4a7-6b/s500x750/8b97317d8f8e0efecb2b1f0b817ad04ad75d61d5.png" alt="">
          </div>
          <div class="title">
            <h3>Homelander</h3>
            <a href="#">Link</a>
            <span>Post</span>
          </div>
        </div>
      </div>
      <!--Fim single video-->

       <!--Inicio single video-->
       <div class="video">
        <div class="thumbnail">
          <img src="https://legendary-digital-network-assets.s3.amazonaws.com/wp-content/uploads/2022/06/10093529/Homelander-Taco-Bowl-The-Boys.jpg" alt="">
        </div>
        <div class="video-details">
          <div class="author">
            <img src="https://64.media.tumblr.com/fe1749dbc7695c88a4700faf8c2e004a/a267b157ec23e4a7-6b/s500x750/8b97317d8f8e0efecb2b1f0b817ad04ad75d61d5.png" alt="">
          </div>
          <div class="title">
            <h3>Homelander</h3>
            <a href="#">Link</a>
            <span>Post</span>
          </div>
        </div>
      </div>
      <!--Fim single video-->

       <!--Inicio single video-->
       <div class="video">
        <div class="thumbnail">
          <img src="https://legendary-digital-network-assets.s3.amazonaws.com/wp-content/uploads/2022/06/10093529/Homelander-Taco-Bowl-The-Boys.jpg" alt="">
        </div>
        <div class="video-details">
          <div class="author">
            <img src="https://64.media.tumblr.com/fe1749dbc7695c88a4700faf8c2e004a/a267b157ec23e4a7-6b/s500x750/8b97317d8f8e0efecb2b1f0b817ad04ad75d61d5.png" alt="">
          </div>
          <div class="title">
            <h3>Homelander</h3>
            <a href="#">Link</a>
            <span>Post</span>
          </div>
        </div>
      </div>
      <!--Fim single video-->
    </div>
  </div>