<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.2/css/all.min.css" integrity="sha512-1sCRPdkRXhBV2PBLUdRb4tMg1w2YPf37qatUFeS7zlBy7jJI8Lf4VHwWfZZfpXtYSLy85pkm9GaYVYMfw5BC1A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
     <link rel="stylesheet" href="/app/views/asset/css/style.css">
    <title>Bem vindo</title>
</head>
<body>
  <!--Começo da header-->
  <div class="header">
       <div class="header-left">
        <i id="menu" class="fa-solid fa-bars"></i>
         <img src="https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/aaa79357-9476-4c1d-b9a8-6e881f2449d3/ddcs83v-0aa3d0b3-75d1-427d-8441-11156de89830.png/v1/fill/w_800,h_310,strp/the_boys_logo_png_by_buffy2ville_ddcs83v-fullview.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9MzEwIiwicGF0aCI6IlwvZlwvYWFhNzkzNTctOTQ3Ni00YzFkLWI5YTgtNmU4ODFmMjQ0OWQzXC9kZGNzODN2LTBhYTNkMGIzLTc1ZDEtNDI3ZC04NDQxLTExMTU2ZGU4OTgzMC5wbmciLCJ3aWR0aCI6Ijw9ODAwIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmltYWdlLm9wZXJhdGlvbnMiXX0.s-4HscwxDVvQee8R6-MH3dHJjhRkAZObBDf2xY8LZDI" alt="">
       </div>

       <div class="header-search">
           <form action="" method="get">
            <input type="text" name="">
            <button><i class="fa-solid fa-magnifying-glass"></i></button>
           </form>
       </div>

       <div class="header_icons">
       <i class="fa-solid fa-magnifying-glass display-this"></i>
       <i class="fa-solid fa-video"></i>
       <i class="fa-solid fa-circle-user"></i>
       <a href="#"><img src="https://i.pinimg.com/originals/cc/ef/1f/ccef1f065d2b429cc7fdbf183506c155.jpg" alt="Avatar Logo" style="width:40px;" class="rounded-pill"></a>
       </div>
  </div>
  <!--Fim da header-->

<!--Começo do mainbody-->
<div class="mainBody">
  <!--Inicio do sidebar-->
  <div class="sidebar">
    <div class="sidebar-categories">
        <div class="sidebar-category">
           <i class="fa-solid fa-house"></i>
           <span>Home</span>
        </div>

        <div class="sidebar-category">
          <i class="fa-solid fa-fire-flame-curved"></i>
           <span>Mais curtidos</span>
        </div>

        <div class="sidebar-category">
           <i class="fa-solid fa-house"></i>
           <span>Home</span>
        </div>
    </div>
    <hr/>

    <div class="sidebar-categories">
        <div class="sidebar-category">
           <i class="fa-solid fa-house"></i>
           <span>Home</span>
        </div>

        <div class="sidebar-category">
          <i class="fa-solid fa-fire-flame-curved"></i>
           <span>Mais curtidos</span>
        </div>

        <div class="sidebar-category">
           <i class="fa-solid fa-house"></i>
           <span>Home</span>
        </div>
    </div>
    <hr/>
  </div>
  <!--Fim do sidebar-->

  <div class="videos">
    <h1>Pense em algo legal</h1>
    <div class="videos-container">
      <!--Inicio single video-->
      <div class="video">
        <div class="thumbnail">
          <img src="https://legendary-digital-network-assets.s3.amazonaws.com/wp-content/uploads/2022/06/10093529/Homelander-Taco-Bowl-The-Boys.jpg" alt="">
        </div>
        <div class="video-details">
          <div class="author">
            <img src="https://64.media.tumblr.com/fe1749dbc7695c88a4700faf8c2e004a/a267b157ec23e4a7-6b/s500x750/8b97317d8f8e0efecb2b1f0b817ad04ad75d61d5.png" alt="">
          </div>
          <div class="title">
            <h3>Homelander</h3>
            <a href="#">Link</a>
            <span>Post</span>
          </div>
        </div>
      </div>
      <!--Fim single video-->

       <!--Inicio single video-->
       <div class="video">
        <div class="thumbnail">
          <img src="https://legendary-digital-network-assets.s3.amazonaws.com/wp-content/uploads/2022/06/10093529/Homelander-Taco-Bowl-The-Boys.jpg" alt="">
        </div>
        <div class="video-details">
          <div class="author">
            <img src="https://64.media.tumblr.com/fe1749dbc7695c88a4700faf8c2e004a/a267b157ec23e4a7-6b/s500x750/8b97317d8f8e0efecb2b1f0b817ad04ad75d61d5.png" alt="">
          </div>
          <div class="title">
            <h3>Homelander</h3>
            <a href="#">Link</a>
            <span>Post</span>
          </div>
        </div>
      </div>
      <!--Fim single video-->

       <!--Inicio single video-->
       <div class="video">
        <div class="thumbnail">
          <img src="https://legendary-digital-network-assets.s3.amazonaws.com/wp-content/uploads/2022/06/10093529/Homelander-Taco-Bowl-The-Boys.jpg" alt="">
        </div>
        <div class="video-details">
          <div class="author">
            <img src="https://64.media.tumblr.com/fe1749dbc7695c88a4700faf8c2e004a/a267b157ec23e4a7-6b/s500x750/8b97317d8f8e0efecb2b1f0b817ad04ad75d61d5.png" alt="">
          </div>
          <div class="title">
            <h3>Homelander</h3>
            <a href="#">Link</a>
            <span>Post</span>
          </div>
        </div>
      </div>
      <!--Fim single video-->

       <!--Inicio single video-->
       <div class="video">
        <div class="thumbnail">
          <img src="https://legendary-digital-network-assets.s3.amazonaws.com/wp-content/uploads/2022/06/10093529/Homelander-Taco-Bowl-The-Boys.jpg" alt="">
        </div>
        <div class="video-details">
          <div class="author">
            <img src="https://64.media.tumblr.com/fe1749dbc7695c88a4700faf8c2e004a/a267b157ec23e4a7-6b/s500x750/8b97317d8f8e0efecb2b1f0b817ad04ad75d61d5.png" alt="">
          </div>
          <div class="title">
            <h3>Homelander</h3>
            <a href="#">Link</a>
            <span>Post</span>
          </div>
        </div>
      </div>
      <!--Fim single video-->

       <!--Inicio single video-->
       <div class="video">
        <div class="thumbnail">
          <img src="https://legendary-digital-network-assets.s3.amazonaws.com/wp-content/uploads/2022/06/10093529/Homelander-Taco-Bowl-The-Boys.jpg" alt="">
        </div>
        <div class="video-details">
          <div class="author">
            <img src="https://64.media.tumblr.com/fe1749dbc7695c88a4700faf8c2e004a/a267b157ec23e4a7-6b/s500x750/8b97317d8f8e0efecb2b1f0b817ad04ad75d61d5.png" alt="">
          </div>
          <div class="title">
            <h3>Homelander</h3>
            <a href="#">Link</a>
            <span>Post</span>
          </div>
        </div>
      </div>
      <!--Fim single video-->

       <!--Inicio single video-->
       <div class="video">
        <div class="thumbnail">
          <img src="https://legendary-digital-network-assets.s3.amazonaws.com/wp-content/uploads/2022/06/10093529/Homelander-Taco-Bowl-The-Boys.jpg" alt="">
        </div>
        <div class="video-details">
          <div class="author">
            <img src="https://64.media.tumblr.com/fe1749dbc7695c88a4700faf8c2e004a/a267b157ec23e4a7-6b/s500x750/8b97317d8f8e0efecb2b1f0b817ad04ad75d61d5.png" alt="">
          </div>
          <div class="title">
            <h3>Homelander</h3>
            <a href="#">Link</a>
            <span>Post</span>
          </div>
        </div>
      </div>
      <!--Fim single video-->
    </div>
  </div>
</div>
<!--Fim do mainbody-->

<script src="/app/views/asset/script/home.js"></script>
</body>
</html>