<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.2/css/all.min.css" integrity="sha512-1sCRPdkRXhBV2PBLUdRb4tMg1w2YPf37qatUFeS7zlBy7jJI8Lf4VHwWfZZfpXtYSLy85pkm9GaYVYMfw5BC1A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <title>Bem vindo</title>
</head>
<body>
<nav class="navbar fixed-top navbar-expand-sm navbar-dark" style="background: #05265B;">
  <div class="container">
    <a class="navbar-brand" href="javascript:void(0)">Logo</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#mynavbar">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="mynavbar">
    <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <a class="nav-link active" href="javascript:void(0)">Link</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="javascript:void(0)">Link</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="javascript:void(0)">Link</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="javascript:void(0)">Link</a>
        </li>

        <li class="nav-item">
          <a class="nav-link active" href="javascript:void(0)">Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="javascript:void(0)">Cadastra-se</a>
        </li>
      </ul>

      <ul class="navbar-nav ms-auto">
      <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle active" href="#" role="button" data-bs-toggle="dropdown"><img src="https://i.pinimg.com/originals/6a/7f/ba/6a7fba865bd67b02a800bc1d60b98686.jpg" alt="Logo" style="width:40px;" class="rounded-pill"></a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Perfil</a></li>
            <li><a class="dropdown-item" href="#">Editar</a></li>
            <li><a class="dropdown-item" href="#">Sair</a></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>
</body>
</html>