<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.2/css/all.min.css" integrity="sha512-1sCRPdkRXhBV2PBLUdRb4tMg1w2YPf37qatUFeS7zlBy7jJI8Lf4VHwWfZZfpXtYSLy85pkm9GaYVYMfw5BC1A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
     <link rel="stylesheet" href="/app/views/asset/css/instagram-style.css">
    <title>Bem vindo</title>
</head>
<body>

<nav class="navbar">
  <div class="nav-wrapper">
    <img src="https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/aaa79357-9476-4c1d-b9a8-6e881f2449d3/ddcs83v-0aa3d0b3-75d1-427d-8441-11156de89830.png/v1/fill/w_800,h_310,strp/the_boys_logo_png_by_buffy2ville_ddcs83v-fullview.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9MzEwIiwicGF0aCI6IlwvZlwvYWFhNzkzNTctOTQ3Ni00YzFkLWI5YTgtNmU4ODFmMjQ0OWQzXC9kZGNzODN2LTBhYTNkMGIzLTc1ZDEtNDI3ZC04NDQxLTExMTU2ZGU4OTgzMC5wbmciLCJ3aWR0aCI6Ijw9ODAwIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmltYWdlLm9wZXJhdGlvbnMiXX0.s-4HscwxDVvQee8R6-MH3dHJjhRkAZObBDf2xY8LZDI" alt="" class="brand-img">
   <form action="" class="search-form">
    <input type="text" name="" id="" class="search-box" placeholder="Pesquise personagens e usuarios">
   </form>
   <div class="nav-items">
      <i class="fa-solid fa-house-chimney"></i>
      <i class="fa-solid fa-house-chimney"></i>
      <i class="fa-solid fa-house-chimney"></i>
      <i class="fa-solid fa-house-chimney"></i>
      <div class="icon user-profile">
       <i class="fa-solid fa-circle-user"></i>
      </div>
   </div>
  </div>
</nav>



<section class="main">
 <div class="wrapper">
    <div class="left-col">
        <div class="status-wrapper">
          <div class="status-card">
              <div class="profile-pic">
                <img src="/app/views/asset/img/person/tumblr_917741aa838a70b74184cd4838bd7b23_ee7f82c4_400.jpg" alt="">
              </div>
              <p class="username">Nome-Usuario</p>
          </div>

          <div class="status-card">
              <div class="profile-pic">
                <img src="/app/views/asset/img/person/tumblr_917741aa838a70b74184cd4838bd7b23_ee7f82c4_400.jpg" alt="">
              </div>
              <p class="username">Nome-Usuario</p>
          </div>

          <div class="status-card">
              <div class="profile-pic">
                <img src="/app/views/asset/img/person/tumblr_917741aa838a70b74184cd4838bd7b23_ee7f82c4_400.jpg" alt="">
              </div>
              <p class="username">Nome-Usuario</p>
          </div>
          <div class="status-card">
              <div class="profile-pic">
                <img src="/app/views/asset/img/person/tumblr_917741aa838a70b74184cd4838bd7b23_ee7f82c4_400.jpg" alt="">
              </div>
              <p class="username">Nome-Usuario</p>
          </div>
          <div class="status-card">
              <div class="profile-pic">
                <img src="/app/views/asset/img/person/tumblr_917741aa838a70b74184cd4838bd7b23_ee7f82c4_400.jpg" alt="">
              </div>
              <p class="username">Nome-Usuario</p>
          </div>
          <div class="status-card">
              <div class="profile-pic">
                <img src="/app/views/asset/img/person/tumblr_917741aa838a70b74184cd4838bd7b23_ee7f82c4_400.jpg" alt="">
              </div>
              <p class="username">Nome-Usuario</p>
          </div>

          <div class="status-card">
              <div class="profile-pic">
                <img src="/app/views/asset/img/person/tumblr_917741aa838a70b74184cd4838bd7b23_ee7f82c4_400.jpg" alt="">
              </div>
              <p class="username">Nome-Usuario</p>
          </div>

          <div class="status-card">
              <div class="profile-pic">
                <img src="/app/views/asset/img/person/tumblr_917741aa838a70b74184cd4838bd7b23_ee7f82c4_400.jpg" alt="">
              </div>
              <p class="username">Nome-Usuario</p>
          </div>
        </div>

        <!--Post-->
          <div class="post">
            <div class="info">
                <div class="user">
                   <div class="profile-pic">
                     <img src="/app/views/asset/img/person/ccef1f065d2b429cc7fdbf183506c155.jpg" alt="">
                      <p class="username">Capitao Patria</p>
                    </div>
                    <i class="fa-solid fa-circle-plus"></i>
                </div>
            </div>
          </div>

    </div>
    <div class="right-col">

    </div>
 </div>
</section>




<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
<script src=""></script>
</body>
</html>